development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV["CABLE_REDIS_URL"] || ENV["REDIS_URL"] %>
  channel_prefix: purecomm_production
  ssl_params:
    verify_mode: 0  # (keeps the TLS self-signed cert error from killing the listener)
