development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV["REDIS_URL"] %>
  channel_prefix: purecomm_production
  ssl_params:
    # OpenSSL::SSL::VERIFY_NONE to work around Heroku Redis cert chain in ActionCable
    verify_mode: 0
